{
    'name': 'Custom Report',
    'summary': """This module Developed for custom report""",
    'version': '1.0.0',
    'description': """This module will add for custom report and access privileged """,
    'author': 'Crystal Technology Bangladesh Ltd.',
    'company': 'cTechbd',
    'website': 'https://www.ctechbd.com',
    'category': 'Tools',
    'depends': ['base', 'sale'],
    'license': 'AGPL-3',
    'sequence': 1,
    'data': [
        # 'security/ir.model.access.csv',
        'views/view.xml',
        'views/view_wizard.xml',
        'report/bill_user_report_view.xml',
        'report/bill_user_report_det_view.xml',
        'report/user_wise_bill_collection_report_view.xml',
        'report/department_wise_bill_collection_report_view.xml',
        # 'views/patient_details.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
